# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/sf_Jan/Dropbox/Code/C++/fiTD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/sf_Jan/Dropbox/Code/C++/fiTD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/sf_Jan/Dropbox/Code/C++/fiTD/CMakeFiles /media/sf_Jan/Dropbox/Code/C++/fiTD/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/sf_Jan/Dropbox/Code/C++/fiTD/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named fitd

# Build rule for target.
fitd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fitd
.PHONY : fitd

# fast build rule for target.
fitd/fast:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/build
.PHONY : fitd/fast

src/CDefinitions.o: src/CDefinitions.cpp.o

.PHONY : src/CDefinitions.o

# target to build an object file
src/CDefinitions.cpp.o:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CDefinitions.cpp.o
.PHONY : src/CDefinitions.cpp.o

src/CDefinitions.i: src/CDefinitions.cpp.i

.PHONY : src/CDefinitions.i

# target to preprocess a source file
src/CDefinitions.cpp.i:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CDefinitions.cpp.i
.PHONY : src/CDefinitions.cpp.i

src/CDefinitions.s: src/CDefinitions.cpp.s

.PHONY : src/CDefinitions.s

# target to generate assembly for a file
src/CDefinitions.cpp.s:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CDefinitions.cpp.s
.PHONY : src/CDefinitions.cpp.s

src/CEnemy.o: src/CEnemy.cpp.o

.PHONY : src/CEnemy.o

# target to build an object file
src/CEnemy.cpp.o:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CEnemy.cpp.o
.PHONY : src/CEnemy.cpp.o

src/CEnemy.i: src/CEnemy.cpp.i

.PHONY : src/CEnemy.i

# target to preprocess a source file
src/CEnemy.cpp.i:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CEnemy.cpp.i
.PHONY : src/CEnemy.cpp.i

src/CEnemy.s: src/CEnemy.cpp.s

.PHONY : src/CEnemy.s

# target to generate assembly for a file
src/CEnemy.cpp.s:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CEnemy.cpp.s
.PHONY : src/CEnemy.cpp.s

src/CGame.o: src/CGame.cpp.o

.PHONY : src/CGame.o

# target to build an object file
src/CGame.cpp.o:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CGame.cpp.o
.PHONY : src/CGame.cpp.o

src/CGame.i: src/CGame.cpp.i

.PHONY : src/CGame.i

# target to preprocess a source file
src/CGame.cpp.i:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CGame.cpp.i
.PHONY : src/CGame.cpp.i

src/CGame.s: src/CGame.cpp.s

.PHONY : src/CGame.s

# target to generate assembly for a file
src/CGame.cpp.s:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CGame.cpp.s
.PHONY : src/CGame.cpp.s

src/CGameEntity.o: src/CGameEntity.cpp.o

.PHONY : src/CGameEntity.o

# target to build an object file
src/CGameEntity.cpp.o:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CGameEntity.cpp.o
.PHONY : src/CGameEntity.cpp.o

src/CGameEntity.i: src/CGameEntity.cpp.i

.PHONY : src/CGameEntity.i

# target to preprocess a source file
src/CGameEntity.cpp.i:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CGameEntity.cpp.i
.PHONY : src/CGameEntity.cpp.i

src/CGameEntity.s: src/CGameEntity.cpp.s

.PHONY : src/CGameEntity.s

# target to generate assembly for a file
src/CGameEntity.cpp.s:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CGameEntity.cpp.s
.PHONY : src/CGameEntity.cpp.s

src/CGameGraphics.o: src/CGameGraphics.cpp.o

.PHONY : src/CGameGraphics.o

# target to build an object file
src/CGameGraphics.cpp.o:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CGameGraphics.cpp.o
.PHONY : src/CGameGraphics.cpp.o

src/CGameGraphics.i: src/CGameGraphics.cpp.i

.PHONY : src/CGameGraphics.i

# target to preprocess a source file
src/CGameGraphics.cpp.i:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CGameGraphics.cpp.i
.PHONY : src/CGameGraphics.cpp.i

src/CGameGraphics.s: src/CGameGraphics.cpp.s

.PHONY : src/CGameGraphics.s

# target to generate assembly for a file
src/CGameGraphics.cpp.s:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CGameGraphics.cpp.s
.PHONY : src/CGameGraphics.cpp.s

src/CGfx.o: src/CGfx.cpp.o

.PHONY : src/CGfx.o

# target to build an object file
src/CGfx.cpp.o:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CGfx.cpp.o
.PHONY : src/CGfx.cpp.o

src/CGfx.i: src/CGfx.cpp.i

.PHONY : src/CGfx.i

# target to preprocess a source file
src/CGfx.cpp.i:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CGfx.cpp.i
.PHONY : src/CGfx.cpp.i

src/CGfx.s: src/CGfx.cpp.s

.PHONY : src/CGfx.s

# target to generate assembly for a file
src/CGfx.cpp.s:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CGfx.cpp.s
.PHONY : src/CGfx.cpp.s

src/CTower.o: src/CTower.cpp.o

.PHONY : src/CTower.o

# target to build an object file
src/CTower.cpp.o:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CTower.cpp.o
.PHONY : src/CTower.cpp.o

src/CTower.i: src/CTower.cpp.i

.PHONY : src/CTower.i

# target to preprocess a source file
src/CTower.cpp.i:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CTower.cpp.i
.PHONY : src/CTower.cpp.i

src/CTower.s: src/CTower.cpp.s

.PHONY : src/CTower.s

# target to generate assembly for a file
src/CTower.cpp.s:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/CTower.cpp.s
.PHONY : src/CTower.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/fitd.dir/build.make CMakeFiles/fitd.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... doc"
	@echo "... fitd"
	@echo "... src/CDefinitions.o"
	@echo "... src/CDefinitions.i"
	@echo "... src/CDefinitions.s"
	@echo "... src/CEnemy.o"
	@echo "... src/CEnemy.i"
	@echo "... src/CEnemy.s"
	@echo "... src/CGame.o"
	@echo "... src/CGame.i"
	@echo "... src/CGame.s"
	@echo "... src/CGameEntity.o"
	@echo "... src/CGameEntity.i"
	@echo "... src/CGameEntity.s"
	@echo "... src/CGameGraphics.o"
	@echo "... src/CGameGraphics.i"
	@echo "... src/CGameGraphics.s"
	@echo "... src/CGfx.o"
	@echo "... src/CGfx.i"
	@echo "... src/CGfx.s"
	@echo "... src/CTower.o"
	@echo "... src/CTower.i"
	@echo "... src/CTower.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

